# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(857, 659)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.previous_image_button = QtWidgets.QPushButton(self.centralwidget)
        self.previous_image_button.setGeometry(QtCore.QRect(90, 490, 151, 51))
        self.previous_image_button.setObjectName("previous_image_button")
        self.next_image_button = QtWidgets.QPushButton(self.centralwidget)
        self.next_image_button.setGeometry(QtCore.QRect(240, 490, 151, 51))
        self.next_image_button.setObjectName("next_image_button")
        self.display_image = QtWidgets.QLabel(self.centralwidget)
        self.display_image.setGeometry(QtCore.QRect(30, 40, 400, 400))
        self.display_image.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.display_image.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.display_image.setLineWidth(20)
        self.display_image.setText("")
        self.display_image.setPixmap(QtGui.QPixmap("../imagis analysis/hw2_handout/cat.jpg"))
        self.display_image.setScaledContents(False)
        self.display_image.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.display_image.setWordWrap(False)
        self.display_image.setObjectName("display_image")
        self.Save = QtWidgets.QPushButton(self.centralwidget)
        self.Save.setGeometry(QtCore.QRect(170, 550, 131, 41))
        self.Save.setObjectName("Save")
        self.Select_button = QtWidgets.QPushButton(self.centralwidget)
        self.Select_button.setGeometry(QtCore.QRect(420, 440, 131, 41))
        self.Select_button.setObjectName("Select_button")
        self.scale = QtWidgets.QSlider(self.centralwidget)
        self.scale.setGeometry(QtCore.QRect(660, 190, 22, 160))
        self.scale.setOrientation(QtCore.Qt.Vertical)
        self.scale.setObjectName("scale")
        self.Brightness = QtWidgets.QSlider(self.centralwidget)
        self.Brightness.setGeometry(QtCore.QRect(790, 190, 22, 160))
        self.Brightness.setOrientation(QtCore.Qt.Vertical)
        self.Brightness.setObjectName("Brightness")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 857, 26))
        self.menubar.setObjectName("menubar")
        self.menuside = QtWidgets.QMenu(self.menubar)
        self.menuside.setObjectName("menuside")
        self.menuFilters = QtWidgets.QMenu(self.menubar)
        self.menuFilters.setObjectName("menuFilters")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_FIles = QtWidgets.QAction(MainWindow)
        self.actionLoad_FIles.setObjectName("actionLoad_FIles")
        self.actionLoad_Folder = QtWidgets.QAction(MainWindow)
        self.actionLoad_Folder.setObjectName("actionLoad_Folder")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionEdge_map = QtWidgets.QAction(MainWindow)
        self.actionEdge_map.setObjectName("actionEdge_map")
        self.actionBilinear_Upscaling = QtWidgets.QAction(MainWindow)
        self.actionBilinear_Upscaling.setObjectName("actionBilinear_Upscaling")
        self.menuside.addSeparator()
        self.menuside.addAction(self.actionLoad_FIles)
        self.menuside.addSeparator()
        self.menuside.addAction(self.actionLoad_Folder)
        self.menuside.addAction(self.actionSave)
        self.menuside.addAction(self.actionSave_as)
        self.menuFilters.addAction(self.actionEdge_map)
        self.menuFilters.addAction(self.actionBilinear_Upscaling)
        self.menubar.addAction(self.menuside.menuAction())
        self.menubar.addAction(self.menuFilters.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.previous_image_button.setText(_translate("MainWindow", "<"))
        self.next_image_button.setText(_translate("MainWindow", ">"))
        self.Save.setText(_translate("MainWindow", "Save"))
        self.Select_button.setText(_translate("MainWindow", "Select image"))
        self.menuside.setTitle(_translate("MainWindow", "File"))
        self.menuFilters.setTitle(_translate("MainWindow", "Filters"))
        self.actionLoad_FIles.setText(_translate("MainWindow", "Load Files"))
        self.actionLoad_Folder.setText(_translate("MainWindow", "Load Folder"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionEdge_map.setText(_translate("MainWindow", "Edge map"))
        self.actionBilinear_Upscaling.setText(_translate("MainWindow", "Bilinear Upscaling"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
